# DO NOT change the config-version option.
config-version: 2

messages:
  # The prefix to use for messages sent to players.
  prefix: '&0[&7AlphaChest&0]'
  
  # The color to for text when sending certain types of messages to players.
  # Color codes reference: http://minecraft.gamepedia.com/Formatting_codes#Color_codes
  colors:
    info: '&f'
    success: '&2'
    warning: '&6'
    error: '&4'
    misc: '&1'

auto-save:
  # Set this to false to disable auto-saving chests.
  enabled: true
  
  # Interval (in minutes) the plugin should save the changed chests to disk.
  interval: 10
  
  # Set this to true to suppress log messages while auto-saving chests.
  silent: false
  
death:
  # Set this to true to clear a player's chest on death if he does not have the "alphachest.death.keep" permission.
  clear: false
  
  # Set this to true to drop the contents of the player's chest on death if he does not have the "alphachest.death.keep" permission.
  drop: false